In [25]:
n=input("Enter values").split()
def three():
    for i in range(len(n)):
        n[i]=int(n[i])
        if(n[i]%3==0 or n[i]%5==0 or n[i]%7==0):
            print(n[i])
three()      

Enter values12 0 6
12
0
6


# Data science
### NumPy-Numerical Python 
### Pandas-Data Frames and Series
### MatPloltLib-Visualization
### Seaborn-makes difficult task easy
### IPython- Interactive python


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [6]:
a_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(a_2d)
type(a)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [7]:
li=[1,3,4,5]
l_a=np.array(li)
print(l_a)

[1 3 4 5]


### ndim - returns the no of dimensions of the array
### shape -  returns the length of array
### size - returns size of array
### itemsize -  returns size of an element or item
### dtype - returns the type oa an array

In [10]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
n=np.random.randint(0,100,10)
print(n)
print(n.ndim)
print(n.size)
print(n.shape)
print(n.itemsize)
print(n.dtype)

[74 53 80 35 44 88 36  8 28 51]
1
10
(10,)
4
int32


In [31]:
n=np.random.randint(0,100,size=24).reshape(3,8)
print(n)
print(n.ndim)
print(n.size)
print(n.shape)
print(n.itemsize)
print(n.dtype)
print()
print(n[::-1])

[[70 60 48  8 50 17 34 77]
 [52 36 86 99 84 47 39 29]
 [75 40 88 77 19 50  5 68]]
2
24
(3, 8)
4
int32

[[75 40 88 77 19 50  5 68]
 [52 36 86 99 84 47 39 29]
 [70 60 48  8 50 17 34 77]]


In [35]:
n=np.ones(9)
print(n)
m=np.zeros(10)
print(m)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np
k=np.linspace(0,2,7)
print(k)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


In [39]:
f=np.full((2,2,),7)#creates concstant element
print(f)

[[7 7]
 [7 7]]


In [42]:
e=np.eye(5)#identity array of given size
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
e1=np.empty((5,2))#in replace of 4 we can put any value then we get previously defined array values
print(e1)

[[3.56043053e-307 1.60219306e-306]
 [7.56571288e-307 1.89146896e-307]
 [1.37961302e-306 1.05699242e-307]
 [8.01097889e-307 1.42419530e-306]
 [8.34445138e-308 2.29179042e-312]]


In [61]:
c=np.array([[[2,4,5],[9,64,56]]])
print(c.ndim)
print(c)
c.reshape(1,6)

3
[[[ 2  4  5]
  [ 9 64 56]]]


array([[ 2,  4,  5,  9, 64, 56]])

In [57]:
c.ravel()

array([ 2,  4,  5,  9, 64, 56])

In [72]:
a=34
b=67
print(np.subtract(a,b))
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(100))
print(np.sin(b))
print(np.cos(b))
print(np.exp(64))
print(np.log(10))

-33
101
2278
0.5074626865671642
10.0
-0.8555199789753223
-0.5177697997895051
6.235149080811617e+27
2.302585092994046


In [6]:
a=np.arange(18).reshape(3,6)
print(a)
print("min",a.min())
print("max",a.max())
print("row wise max",a.max(axis=0))#axis=0 then row and axis=1 then column wise
print("column wise max",a.max(axis=1))
print("total sum",a.sum())
print("cumulative sum",a.cumsum())#cumulative sum
print("mean of a",np.mean(a))
print("median of a",np.median(a))
print(np.std(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
min 0
max 17
row wise max [12 13 14 15 16 17]
column wise max [ 5 11 17]
total sum 153
cumulative sum [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153]
mean of a 8.5
median of a 8.5
5.188127472091127


In [97]:
sa=np.array([23,23,11,1,3,7,656])
sa.sort()

In [99]:
print(sa)

[  1   3   7  11  23  23 656]


In [112]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
print(" \n",sa)
print("transpose\n",sa.transpose())
sa.T# used for transpose

 
 [[ 23  23  11]
 [  2   9   0]
 [  1   7 656]]
transpose
 [[ 23   2   1]
 [ 23   9   7]
 [ 11   0 656]]


array([[ 23,   2,   1],
       [ 23,   9,   7],
       [ 11,   0, 656]])

In [115]:
print(np.hsplit(sa,3))#horizontal split

[array([[23],
       [ 2],
       [ 1]]), array([[23],
       [ 9],
       [ 7]]), array([[ 11],
       [  0],
       [656]])]


In [123]:
print(np.vsplit(sa,3))#vertical split

[array([[23, 23, 11]]), array([[2, 9, 0]]), array([[  1,   7, 656]])]


In [124]:
a=np.array([1,2,3,34,5,6,7,9,8])
a

array([ 1,  2,  3, 34,  5,  6,  7,  9,  8])

In [127]:
np.hsplit(a,1)

[array([ 1,  2,  3, 34,  5,  6,  7,  9,  8])]

In [132]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
sa[0]

array([23, 23, 11])

In [133]:
sa[0:2]

array([[23, 23, 11],
       [ 2,  9,  0]])

In [134]:
sa[0:3]

array([[ 23,  23,  11],
       [  2,   9,   0],
       [  1,   7, 656]])

In [137]:
sa[0:2,0]# it returns the first element in specified rows

array([23,  2])

In [148]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
for i in range(np.ndim(sa)):
    for j in range(np.ndim(sa[i])):
        if(j==4):
            print(j)

In [145]:
sa[2,2]

656

In [171]:
a=np.random.randint(1,100,50)
print("max:\t",a.max())
print("min:\t",a.min())
print("mean:\t",a.mean())
print("median:\t",np.max(a))
print("sd:\t",np.std(a))
print("sum:\t",a.sum())
print("cumulative sum:\t",a.cumsum())
print("sorting:\t",a.ravel())
print("hsplit:\t",np.hsplit(a,5))
print("transpose\n",a.T)

max:	 94
min:	 2
mean:	 46.9
median:	 94
sd:	 29.153558959413512
sum:	 2345
cumulative sum:	 [  81   85  132  148  207  220  224  227  307  375  439  501  572  666
  735  786  830  919  957 1029 1113 1180 1218 1308 1331 1373 1426 1463
 1469 1501 1542 1544 1582 1595 1610 1668 1758 1845 1858 1877 1912 1992
 2031 2087 2094 2097 2180 2261 2271 2345]
sorting:	 [81  4 47 16 59 13  4  3 80 68 64 62 71 94 69 51 44 89 38 72 84 67 38 90
 23 42 53 37  6 32 41  2 38 13 15 58 90 87 13 19 35 80 39 56  7  3 83 81
 10 74]
hsplit:	 [array([81,  4, 47, 16, 59, 13,  4,  3, 80, 68]), array([64, 62, 71, 94, 69, 51, 44, 89, 38, 72]), array([84, 67, 38, 90, 23, 42, 53, 37,  6, 32]), array([41,  2, 38, 13, 15, 58, 90, 87, 13, 19]), array([35, 80, 39, 56,  7,  3, 83, 81, 10, 74])]
transpose
 [81  4 47 16 59 13  4  3 80 68 64 62 71 94 69 51 44 89 38 72 84 67 38 90
 23 42 53 37  6 32 41  2 38 13 15 58 90 87 13 19 35 80 39 56  7  3 83 81
 10 74]


In [172]:
np.ones(3,3)

TypeError: data type not understood

In [8]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

In [2]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [3]:
dir(NumPy)

NameError: name 'NumPy' is not defined